# Generated by Django 5.2.16 on 2026-08-06 20:02

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("identity", "0005_manager_invitation_delivery"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SEQUENCE event_sequence_number_seq AS bigint",
            "DROP SEQUENCE IF EXISTS event_sequence_number_seq",
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_number",
                    models.BigIntegerField(
                        db_default=django.db.models.expressions.RawSQL(
                            "nextval('event_sequence_number_seq'::regclass)", ()
                        ),
                        unique=True,
                    ),
                ),
                ("event_type", models.TextField()),
                ("occurred_at", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_default=django.db.models.expressions.RawSQL("now()", ())
                    ),
                ),
                (
                    "actor_type",
                    models.TextField(
                        choices=[
                            ("user", "User"),
                            ("system", "System"),
                            ("scheduled_process", "Scheduled process"),
                            ("external_system", "External system"),
                        ]
                    ),
                ),
                ("primary_subject_type", models.TextField(blank=True, null=True)),
                ("primary_subject_id", models.BigIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(db_default={}, default=dict)),
                ("idempotency_key", models.TextField(blank=True, null=True)),
                ("correlation_key", models.TextField(blank=True, null=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="domain_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "causation_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="caused_events",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "event",
            },
        ),
        migrations.CreateModel(
            name="EventNotificationIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_default="pending",
                        default="pending",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(db_default=0, default=0)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.expressions.RawSQL("now()", ())
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notification_intent",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "event_notification_intent",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_snapshot", models.TextField()),
                ("body_snapshot", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_default="unread",
                        default="unread",
                    ),
                ),
                ("pinned", models.BooleanField(db_default=False, default=False)),
                ("important", models.BooleanField(db_default=False, default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.expressions.RawSQL("now()", ())
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notifications",
                        to="events.event",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification",
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["event_type"], name="idx_009_event_type"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["primary_subject_type", "primary_subject_id"],
                name="idx_010_event_subject",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                condition=models.Q(("correlation_key__isnull", False)),
                fields=["correlation_key"],
                name="idx_011_event_correlation",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["causation_event"], name="idx_012_event_causation"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "actor_type__in",
                        ("user", "system", "scheduled_process", "external_system"),
                    )
                ),
                name="cst_033_event_actor_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("actor_type", "user"), _negated=True),
                    ("actor_user__isnull", False),
                    _connector="OR",
                ),
                name="cst_034_event_user_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("event_type", "idempotency_key"),
                name="cst_036_event_producer_key_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="eventnotificationintent",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["created_at"],
                name="idx_013_event_intent_pending",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventnotificationintent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "processing", "processed", "failed"))
                ),
                name="cst_682_event_intent_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventnotificationintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts__gte", 0), ("attempts__lte", 3)),
                name="cst_683_event_intent_attempts",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventnotificationintent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("attempts", 0), ("last_attempted_at__isnull", True)),
                    models.Q(("attempts__gt", 0), ("last_attempted_at__isnull", False)),
                    _connector="OR",
                ),
                name="cst_684_event_intent_attempt_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient_user", "status"], name="idx_014_notification_inbox"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("unread", "read", "dismissed"))),
                name="cst_685_notification_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("event", "recipient_user"),
                name="cst_037_notification_event_recipient_uniq",
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION event_immutable_guard() RETURNS trigger
                LANGUAGE plpgsql AS $$
                BEGIN
                    RAISE EXCEPTION 'event rows are immutable' USING ERRCODE = '55000';
                END;
                $$;
                CREATE TRIGGER trg_event_immutable
                BEFORE UPDATE OR DELETE ON event
                FOR EACH ROW EXECUTE FUNCTION event_immutable_guard();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trg_event_immutable ON event;
                DROP FUNCTION IF EXISTS event_immutable_guard();
            """,
        ),
    ]
