# Generated by Django 5.2.16 on 2026-08-06 09:12

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models

import identity.managers


class Migration(migrations.Migration):
    initial = True

    run_before = [
        ("auth", "0001_initial"),
        ("sessions", "0001_initial"),
    ]

    dependencies = [
        ("workshops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.TextField()),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("date_of_birth", models.DateField()),
                ("avatar_path", models.TextField(blank=True, null=True)),
                ("email", models.TextField()),
                ("phone", models.TextField(blank=True, null=True)),
                (
                    "account_role",
                    models.TextField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("operator", "Operator"),
                        ]
                    ),
                ),
                (
                    "onboarding_state",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("registered_no_workshop", "Registered without workshop")
                        ],
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ]
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.expressions.RawSQL("now()", ()),
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, default=1)),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="users",
                        to="workshops.workshop",
                    ),
                ),
                (
                    "workshop_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="users",
                        to="workshops.workshoprole",
                    ),
                ),
            ],
            options={
                "db_table": "user_account",
                "indexes": [
                    models.Index(
                        fields=["workshop", "status", "account_role"],
                        name="idx_006_user_list",
                    ),
                    models.Index(fields=["workshop_role"], name="idx_007_user_role"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("account_role__in", ("admin", "manager", "operator"))
                        ),
                        name="cst_017_user_account_role",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ("pending", "active", "inactive"))
                        ),
                        name="cst_018_user_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("first_name", ""), _negated=True),
                            models.Q(("last_name", ""), _negated=True),
                        ),
                        name="cst_015_user_names_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="cst_019_user_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "inactive"), _negated=True),
                            ("account_role", "operator"),
                            _connector="OR",
                        ),
                        name="cst_023_user_inactive_operator",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("account_role", "admin"),
                                ("onboarding_state", "registered_no_workshop"),
                                ("status", "active"),
                                ("workshop__isnull", True),
                                ("workshop_role__isnull", True),
                            ),
                            models.Q(
                                ("onboarding_state__isnull", True),
                                ("workshop__isnull", False),
                                ("workshop_role__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="cst_663_user_attachment_shape",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="cst_016_user_email_lower_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("id", "workshop"), name="cst_021_user_id_workshop_uniq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("account_role", "admin"), ("status", "active")
                        ),
                        fields=("workshop",),
                        name="cst_024_user_active_admin_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("account_role", "manager")),
                        fields=("workshop",),
                        name="cst_025_user_manager_uniq",
                    ),
                ],
            },
            managers=[
                ("objects", identity.managers.UserManager()),
            ],
        ),
    ]
