# Generated by Django 5.2.16 on 2026-08-06 16:54

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models

FORWARD_SQL = r"""
ALTER TABLE public.user_invitation
ADD CONSTRAINT cst_665_user_invitation_token_shape
CHECK (octet_length(token_hash) = 32 AND octet_length(token_salt) > 0);

ALTER TABLE public.user_invitation
ADD CONSTRAINT cst_665_user_invitation_candidate_scope_fk
FOREIGN KEY (user_id, workshop_id)
REFERENCES public.user_account(id, workshop_id) ON DELETE CASCADE;

ALTER TABLE public.manager_invitation_command_receipt
ADD CONSTRAINT cst_676_manager_receipt_candidate_fk
FOREIGN KEY (candidate_user_id) REFERENCES public.user_account(id) ON DELETE CASCADE;

ALTER TABLE public.manager_invitation_command_receipt
ADD CONSTRAINT cst_676_manager_receipt_invitation_fk
FOREIGN KEY (result_invitation_id) REFERENCES public.user_invitation(id) ON DELETE CASCADE;

CREATE FUNCTION public.sb04_manager_receipt_guard()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $function$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NOT EXISTS (
            SELECT 1 FROM public.user_invitation invitation
            WHERE invitation.id = NEW.result_invitation_id
              AND invitation.user_id = NEW.candidate_user_id
              AND invitation.workshop_id = NEW.workshop_id
        ) THEN
            RAISE EXCEPTION 'manager invitation receipt relationship is invalid'
                USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' AND pg_trigger_depth() > 1 THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'manager invitation receipt is immutable' USING ERRCODE = '23514';
END;
$function$;

CREATE TRIGGER cst_676_manager_receipt_guard
BEFORE INSERT OR UPDATE OR DELETE ON public.manager_invitation_command_receipt
FOR EACH ROW EXECUTE FUNCTION public.sb04_manager_receipt_guard();

CREATE FUNCTION public.sb04_email_delivery_transition_guard()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $function$
BEGIN
    IF NEW.status = 'pending' AND NEW.attempt_count = 0
       AND NEW.last_attempted_at IS NULL THEN
        IF TG_OP = 'INSERT' THEN RETURN NEW; END IF;
        RAISE EXCEPTION 'delivery intent cannot return to unclaimed pending'
            USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' THEN
        IF OLD.status = 'pending' AND OLD.attempt_count = 0
           AND NEW.status = 'pending' AND NEW.attempt_count = 1
           AND NEW.last_attempted_at IS NOT NULL THEN RETURN NEW; END IF;
        IF OLD.status = 'pending' AND OLD.attempt_count IN (0, 1)
           AND NEW.status = 'superseded'
           AND NEW.attempt_count = OLD.attempt_count
           AND NEW.last_attempted_at IS NOT DISTINCT FROM OLD.last_attempted_at
           THEN RETURN NEW; END IF;
        IF OLD.status = 'pending' AND OLD.attempt_count = 1
           AND NEW.status IN ('sent', 'failed')
           AND NEW.attempt_count = 1
           AND NEW.last_attempted_at = OLD.last_attempted_at THEN RETURN NEW; END IF;
    END IF;
    RAISE EXCEPTION 'invalid delivery intent transition' USING ERRCODE = '23514';
END;
$function$;

CREATE TRIGGER cst_668_email_delivery_transition_guard
BEFORE INSERT OR UPDATE ON public.email_delivery_intent
FOR EACH ROW EXECUTE FUNCTION public.sb04_email_delivery_transition_guard();
"""

REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS cst_668_email_delivery_transition_guard
ON public.email_delivery_intent;
DROP FUNCTION IF EXISTS public.sb04_email_delivery_transition_guard();
DROP TRIGGER IF EXISTS cst_676_manager_receipt_guard
ON public.manager_invitation_command_receipt;
DROP FUNCTION IF EXISTS public.sb04_manager_receipt_guard();
ALTER TABLE public.manager_invitation_command_receipt
DROP CONSTRAINT IF EXISTS cst_676_manager_receipt_invitation_fk;
ALTER TABLE public.manager_invitation_command_receipt
DROP CONSTRAINT IF EXISTS cst_676_manager_receipt_candidate_fk;
ALTER TABLE public.user_invitation
DROP CONSTRAINT IF EXISTS cst_665_user_invitation_candidate_scope_fk;
ALTER TABLE public.user_invitation
DROP CONSTRAINT IF EXISTS cst_665_user_invitation_token_shape;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_workshop_establishment"),
        ("workshops", "0003_seed_protected_identities"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.BinaryField(unique=True)),
                (
                    "token_hash_version",
                    models.SmallIntegerField(db_default=1, default=1),
                ),
                ("token_salt", models.BinaryField()),
                (
                    "invitation_generation",
                    models.PositiveIntegerField(db_default=1, default=1),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("consumed", "Consumed"),
                            ("recalled", "Recalled"),
                        ],
                        db_default="pending",
                        default="pending",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.expressions.RawSQL("now()", ())
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_invitations",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "db_table": "user_invitation",
            },
        ),
        migrations.CreateModel(
            name="ManagerInvitationCommandReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.TextField()),
                ("fingerprint_version", models.SmallIntegerField()),
                ("payload_fingerprint", models.BinaryField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.expressions.RawSQL("now()", ())
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="manager_invitation_receipts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate_user",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="manager_invitation_receipt",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="manager_invitation_receipts",
                        to="workshops.workshop",
                    ),
                ),
                (
                    "result_invitation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="command_receipts",
                        to="identity.userinvitation",
                    ),
                ),
            ],
            options={
                "db_table": "manager_invitation_command_receipt",
            },
        ),
        migrations.CreateModel(
            name="EmailDeliveryIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(db_default="invitation", default="invitation"),
                ),
                ("recipient_email", models.TextField()),
                ("invitation_generation", models.PositiveIntegerField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("superseded", "Superseded"),
                        ],
                        db_default="pending",
                        default="pending",
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(db_default=0, default=0)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.expressions.RawSQL("now()", ())
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_intents",
                        to="identity.userinvitation",
                    ),
                ),
            ],
            options={
                "db_table": "email_delivery_intent",
            },
        ),
        migrations.AddIndex(
            model_name="userinvitation",
            index=models.Index(fields=["user"], name="idx_004_invitation_user"),
        ),
        migrations.AddIndex(
            model_name="userinvitation",
            index=models.Index(
                fields=["status", "expires_at"], name="idx_005_invitation_expiry"
            ),
        ),
        migrations.AddConstraint(
            model_name="userinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("pending", "consumed", "recalled"))),
                name="cst_028_user_invitation_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="cst_030_user_invitation_expiry",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user",),
                name="cst_031_user_pending_invitation_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("token_hash_version__gt", 0),
                    ("invitation_generation__gt", 0),
                    ("expires_at__gt", models.F("issued_at")),
                ),
                name="cst_665_user_invitation_generation",
            ),
        ),
        migrations.AddConstraint(
            model_name="managerinvitationcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("fingerprint_version__gt", 0)),
                name="cst_676_manager_invite_fingerprint_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="managerinvitationcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("workshop", "idempotency_key"),
                name="cst_677_manager_invite_receipt_key_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliveryintent",
            index=models.Index(
                fields=["status", "created_at"], name="idx_008_delivery_monitor"
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildeliveryintent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("purpose", "invitation"),
                    models.Q(("recipient_email", ""), _negated=True),
                    ("invitation_generation__gt", 0),
                    ("status__in", ("pending", "sent", "failed", "superseded")),
                    ("attempt_count__gte", 0),
                    ("attempt_count__lte", 1),
                    models.Q(
                        models.Q(
                            ("attempt_count", 0), ("last_attempted_at__isnull", True)
                        ),
                        models.Q(
                            ("attempt_count", 1), ("last_attempted_at__isnull", False)
                        ),
                        _connector="OR",
                    ),
                ),
                name="cst_666_email_delivery_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildeliveryintent",
            constraint=models.UniqueConstraint(
                fields=("invitation", "invitation_generation"),
                name="cst_667_email_delivery_generation_uniq",
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
