# Generated by Django 5.2.16 on 2026-08-06 09:12

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("address", models.TextField()),
                ("email", models.TextField()),
                ("timezone", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("manager_required", "Manager required"),
                            (
                                "manager_activation_pending",
                                "Manager activation pending",
                            ),
                            ("operational", "Operational"),
                        ],
                        default="manager_required",
                        db_default="manager_required",
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, default=1)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.expressions.RawSQL("now()", ()),
                    ),
                ),
                (
                    "timezone_correction_idempotency_key",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "station_code_counter",
                    models.PositiveIntegerField(db_default=0, default=0),
                ),
                (
                    "customer_code_counter",
                    models.PositiveIntegerField(db_default=0, default=0),
                ),
                (
                    "order_code_counter",
                    models.PositiveIntegerField(db_default=0, default=0),
                ),
                (
                    "build_code_counter",
                    models.PositiveIntegerField(db_default=0, default=0),
                ),
            ],
            options={
                "db_table": "workshop",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                (
                                    "manager_required",
                                    "manager_activation_pending",
                                    "operational",
                                ),
                            )
                        ),
                        name="cst_001_workshop_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="cst_003_workshop_version_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("timezone_correction_idempotency_key",),
                        name="cst_006_workshop_timezone_key_uniq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_production", models.BooleanField()),
                (
                    "requires_clearance",
                    models.BooleanField(db_default=True, default=True),
                ),
                ("machine_key", models.TextField(blank=True, null=True)),
                ("first_referenced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        default="active",
                        db_default="active",
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, default=1)),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="operation_types",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "db_table": "operation_type",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("active", "retired"))),
                        name="cst_047_operation_type_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="cst_038_operation_type_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("machine_key__isnull", True),
                            ("status", "active"),
                            _connector="OR",
                        ),
                        name="cst_045_operation_type_protected_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("workshop__isnull", True),
                            models.Q(("name__iexact", "other"), _negated=True),
                            _connector="OR",
                        ),
                        name="cst_048_operation_type_other_reserved",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="cst_049_operation_type_name_nonempty",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("workshop"),
                        condition=models.Q(("workshop__isnull", False)),
                        name="cst_041_operation_type_name_uniq",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        condition=models.Q(("workshop__isnull", True)),
                        name="cst_042_global_operation_type_name_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("workshop__isnull", True)),
                        fields=("machine_key",),
                        name="cst_043_global_operation_type_key_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("machine_key__isnull", False), ("workshop__isnull", False)
                        ),
                        fields=("workshop", "machine_key"),
                        name="cst_044_workshop_operation_type_key_uniq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkshopRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("machine_key", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        default="active",
                        db_default="active",
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, default=1)),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="roles",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "db_table": "workshop_role",
                "indexes": [
                    models.Index(
                        fields=["workshop", "status"],
                        name="idx_003_workshop_role_scope",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("active", "retired"))),
                        name="cst_007_workshop_role_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="cst_008_workshop_role_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("machine_key__isnull", True),
                            ("status", "active"),
                            _connector="OR",
                        ),
                        name="cst_012_workshop_role_sentinel_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("workshop__isnull", True),
                            models.Q(
                                models.Q(("name__iexact", "undefined"), _negated=True),
                                models.Q(("name__iexact", "admin"), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="cst_013_workshop_role_reserved_names",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("workshop"),
                        condition=models.Q(("workshop__isnull", False)),
                        name="cst_009_workshop_role_name_uniq",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        condition=models.Q(("workshop__isnull", True)),
                        name="cst_010_global_workshop_role_name_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("machine_key",), name="cst_011_workshop_role_key_uniq"
                    ),
                ],
            },
        ),
    ]
