# Generated by Django 5.2.16 on 2026-07-14 20:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clearances',
            field=models.ManyToManyField(blank=True, related_name='cleared_users', to='catalog.operationtype'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('on_leave', 'On leave'), ('inactive', 'Inactive')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='catalog.workshop'),
        ),
        migrations.AddField(
            model_name='user',
            name='workshop_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='catalog.workshoprole'),
        ),
    ]
