# Generated by Django 5.2.16 on 2026-07-16 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_fields'),
        ('catalog', '0004_alter_station_code_station_uq_station_workshop_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=16)),
                ('target_type', models.CharField(choices=[('user', 'User')], max_length=20)),
                ('target_id', models.PositiveBigIntegerField()),
                ('target_field', models.CharField(max_length=32)),
                ('current_value', models.CharField(blank=True, max_length=255)),
                ('proposed_value', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cancel_reason', models.CharField(blank=True, choices=[('superseded', 'Superseded'), ('requester_deactivated', 'Requester deactivated')], max_length=32, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_change_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_change_requests', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='catalog.workshop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workshop', 'code'), name='uq_changerequest_workshop_code'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('requested_by',), name='uniq_pending_cr_per_requester')],
            },
        ),
    ]
