# Generated by Django 5.2.16 on 2026-07-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_production', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='catalog.materialcategory')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='catalog.unittype')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='catalog.workshop')),
            ],
        ),
        migrations.AddField(
            model_name='unittype',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to='catalog.workshop'),
        ),
        migrations.CreateModel(
            name='StationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=32)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_categories', to='catalog.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('scheduled_for_maint', 'Scheduled for maintenance'), ('under_maintenance', 'Under maintenance'), ('broken', 'Broken'), ('offline', 'Offline'), ('retired', 'Retired')], default='active', max_length=32)),
                ('maint_start', models.DateField(blank=True, null=True)),
                ('maint_end', models.DateField(blank=True, null=True)),
                ('maint_reason', models.CharField(blank=True, max_length=255)),
                ('supported_operations', models.ManyToManyField(blank=True, related_name='stations', to='catalog.operationtype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='catalog.stationcategory')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='catalog.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.JSONField(default=list)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_definitions', to='catalog.workshop')),
            ],
        ),
        migrations.AddField(
            model_name='operationtype',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_types', to='catalog.workshop'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_categories', to='catalog.workshop'),
        ),
        migrations.CreateModel(
            name='WorkshopRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('default_clearances', models.ManyToManyField(blank=True, related_name='default_in_roles', to='catalog.operationtype')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_roles', to='catalog.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_label', models.CharField(max_length=100)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('min_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('lot_sizes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.material')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('material', 'spec_label'), name='uq_materialvariant_material_spec_label')],
            },
        ),
        migrations.AddConstraint(
            model_name='unittype',
            constraint=models.UniqueConstraint(fields=('workshop', 'name'), name='uq_unittype_workshop_name'),
        ),
        migrations.AddConstraint(
            model_name='unittype',
            constraint=models.UniqueConstraint(fields=('workshop', 'abbreviation'), name='uq_unittype_workshop_abbreviation'),
        ),
        migrations.AddConstraint(
            model_name='stationcategory',
            constraint=models.UniqueConstraint(fields=('workshop', 'name'), name='uq_stationcategory_workshop_name', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='stationcategory',
            constraint=models.UniqueConstraint(fields=('workshop', 'colour'), name='uq_stationcategory_workshop_colour', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('workshop', 'name'), name='uq_station_workshop_name'),
        ),
        migrations.AddConstraint(
            model_name='shiftdefinition',
            constraint=models.UniqueConstraint(fields=('workshop', 'name'), name='uq_shiftdefinition_workshop_name'),
        ),
        migrations.AddConstraint(
            model_name='shiftdefinition',
            constraint=models.UniqueConstraint(fields=('workshop', 'start_time', 'end_time', 'days'), name='uq_shiftdefinition_workshop_window'),
        ),
        migrations.AddConstraint(
            model_name='operationtype',
            constraint=models.UniqueConstraint(fields=('workshop', 'name'), name='uq_operationtype_workshop_name'),
        ),
        migrations.AddConstraint(
            model_name='materialcategory',
            constraint=models.UniqueConstraint(fields=('workshop', 'name'), name='uq_materialcategory_workshop_name', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('workshop', 'name'), name='uq_material_workshop_name'),
        ),
        migrations.AddConstraint(
            model_name='workshoprole',
            constraint=models.UniqueConstraint(fields=('workshop', 'name'), name='uq_workshoprole_workshop_name', nulls_distinct=False),
        ),
    ]
