# Generated by Django 5.2.16 on 2026-07-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_system_seeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialvariant',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='materialvariant',
            name='min_threshold',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
