# Generated by Django 5.2.16 on 2026-07-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_materialvariant_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('workshop', 'code'), name='uq_station_workshop_code'),
        ),
    ]
