# Generated by Django 5.2.16 on 2026-07-16 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='unread', max_length=20)),
                ('pinned', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('clearance_changed', 'Clearance changed'), ('account', 'Account'), ('clr_pending_manager', 'Clearance request pending manager'), ('clr_pending_admin', 'Clearance request pending admin'), ('clr_manager_approved', 'Clearance request manager-approved'), ('clr_approved', 'Clearance request approved'), ('clr_rejected', 'Clearance request rejected'), ('clr_cancelled', 'Clearance request cancelled'), ('cr_rejected', 'Change request rejected'), ('station_breakdown', 'Station breakdown'), ('station_maintenance', 'Station maintenance'), ('station_offline', 'Station offline'), ('station_available', 'Station available'), ('station_retired', 'Station retired'), ('capability_lost', 'Capability lost'), ('op_assigned', 'Operation assigned'), ('op_rescheduled', 'Operation rescheduled'), ('op_unassigned', 'Operation unassigned'), ('op_blocked', 'Operation blocked'), ('due_date_breach', 'Due-date breach'), ('op_partial', 'Operation partially complete'), ('reschedule_suggestion', 'Reschedule suggestion'), ('leave_submitted', 'Leave submitted'), ('leave_approved', 'Leave approved'), ('leave_slots_affected', 'Leave affects schedule'), ('leave_rejected', 'Leave rejected'), ('leave_revoked', 'Leave revoked'), ('leave_schedule_review', 'Leave schedule review'), ('leave_cancelled', 'Leave cancelled'), ('order_ready', 'Order ready'), ('order_cancelled', 'Order cancelled'), ('order_delivered', 'Order delivered'), ('work_item_assigned', 'Work item assigned'), ('work_item_unassigned', 'Work item unassigned'), ('work_item_completed', 'Work item completed'), ('work_item_dismissed', 'Work item dismissed'), ('work_item_source_changed', 'Work item source changed'), ('work_item_cancelled', 'Work item cancelled'), ('stock_out', 'Stock out'), ('stock_replenished', 'Stock replenished'), ('po_arrived', 'Purchase order arrived'), ('po_cancelled', 'Purchase order cancelled'), ('report_raised', 'Report raised'), ('report_resolved', 'Report resolved'), ('report_dismissed', 'Report dismissed'), ('invite_accepted', 'Invitation accepted'), ('invite_expired', 'Invitation expired'), ('message', 'Message')], max_length=32)),
                ('source_type', models.CharField(blank=True, max_length=100, null=True)),
                ('source_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx')],
            },
        ),
    ]
